spring:
  datasource:
    url: jdbc:mysql://localhost:3306/busi_youngzeu?characterEncoding=utf8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: yzredis
    # 连接超时时间（毫秒）
    timeout: 0
    # 2.0.2RELEASE 以上的版本，redis.pool 改成了 redis.jedis.pool, 详见 autoconfigure.data.redis.RedisProperties
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间 ms（使用负值表示没有限制）
        max-wait: 1000
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

server: 
  servlet: 
    context-path: /mplus
  port: 8888

mybatis-plus:
    mapper-locations: classpath:/mapper/*Mapper.xml
    #实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage: com.youngzeu.mplus.entity
    global-config: 
      db-config: 
        #刷新mapper 调试神器
        #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
        id-type: auto
        #驼峰下划线转换
        capital-mode: true
        #逻辑删除配置, 直接在Model(Entity)中的逻辑删除字段加上@TableLogic就行
        # 详细用法参见本项目com.youngzeu.mplus.entity.base.BaseEntity的isDelete字段
#        sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#        logic-delete-value: 0
#        logic-not-delete-value: 1
        db-type: mysql
        # mybatis plus 默认策略NOT_NULL,即更新和新增的时候,只操作notNull的字段
        # IGNORED(忽略判断,可在单个字段上加@TableField(strategy=FieldStrategy.IGNORED)达到效果)
        # NOT_EMPTY(非空判断) DEFAULT(默认NOT_NULL)
        field-strategy: NOT_NULL
        #自定义填充策略接口实现
        #meta-object-handler: com.baomidou.springboot.xxx
        #自定义SQL注入器
        #sql-injector: com.baomidou.springboot.xxx
    configuration: 
        map-underscore-to-camel-case: true
        cache-enabled: false
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.youngzeu : debug

